# Generated by Django 6.0.4 on 2026-06-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_leads_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='model_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
