# Generated by Django 6.0.4 on 2026-06-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_alter_note_model_client_clientactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaisummary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
