# Generated by Django 6.0.4 on 2026-06-20 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_alter_clientaisummary_collabration_strength_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='model',
            field=models.CharField(choices=[('lead', 'Lead'), ('client', 'Client'), ('meeting', 'Meeting'), ('candidate', 'Candidate')], max_length=20),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('current_salary', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=50, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='candidates/resumes')),
                ('status', models.CharField(choices=[('new', 'New'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='agency.agency')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='agency.job')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='CandidateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_activities', to='agency.agency')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='agency.candidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Activity',
                'verbose_name_plural': 'Candidate Activities',
            },
        ),
        migrations.CreateModel(
            name='CandidateAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('key_strength', models.JSONField(blank=True, default=list, null=True)),
                ('potential_concerns', models.JSONField(blank=True, default=list, null=True)),
                ('skills_match', models.FloatField(default=0)),
                ('experience_match', models.FloatField(default=0)),
                ('salary_match', models.FloatField(default=0)),
                ('location_match', models.FloatField(default=0)),
                ('overall_match_percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_ai_analysis', to='agency.agency')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='agency.candidate')),
            ],
            options={
                'verbose_name': 'Candidate AI Analysis',
                'verbose_name_plural': 'Candidate AI Analysis',
            },
        ),
    ]
