# Generated by Django 6.0.4 on 2026-06-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_candidatemeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemeeting',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
