# Generated by Django 6.0.4 on 2026-06-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_extracted_raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
