# Generated by Django 6.0.4 on 2026-06-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_activity'),
    ]

def migrate_old_activities(apps, schema_editor):
    ClientActivity = apps.get_model('agency', 'ClientActivity')
    CandidateActivity = apps.get_model('agency', 'CandidateActivity')
    Activity = apps.get_model('agency', 'Activity')

    activities_to_create = []

    # Copy ClientActivity records
    for ca in ClientActivity.objects.all():
        act = Activity(
            summary=ca.summary,
            model='client',
            model_id=ca.client_id,
            user_id=ca.user_id,
            agency_id=ca.agency_id,
            created_at=ca.created_at,
            updated_at=ca.updated_at
        )
        activities_to_create.append(act)

    # Copy CandidateActivity records
    for ca in CandidateActivity.objects.all():
        act = Activity(
            summary=ca.summary,
            model='candidate',
            model_id=ca.candidate_id,
            user_id=ca.user_id,
            agency_id=ca.agency_id,
            created_at=ca.created_at,
            updated_at=ca.updated_at
        )
        activities_to_create.append(act)

    if activities_to_create:
        Activity.objects.bulk_create(activities_to_create)


def reverse_migrate_old_activities(apps, schema_editor):
    Activity = apps.get_model('agency', 'Activity')
    Activity.objects.filter(model__in=['client', 'candidate']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_activity'),
    ]

    operations = [
        migrations.RunPython(migrate_old_activities, reverse_migrate_old_activities),
    ]

