# Generated by Django 6.0.4 on 2026-06-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0016_migrate_activity_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientactivity',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='clientactivity',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientactivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='CandidateActivity',
        ),
        migrations.DeleteModel(
            name='ClientActivity',
        ),
    ]
