# Generated by Django 6.0.4 on 2026-06-25 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_remove_clientactivity_agency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='model',
            field=models.CharField(choices=[('client', 'Client'), ('candidate', 'Candidate'), ('lead', 'Lead'), ('job', 'Job'), ('member', 'Member'), ('placement', 'Placement'), ('agency', 'Agency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
