# Generated by Django 6.0.4 on 2026-07-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0019_leads_company_domain_leads_company_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
