# Generated by Django 6.0.4 on 2026-07-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0021_alter_candidate_phone_alter_client_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
