# Generated by Django 6.0.4 on 2026-07-25 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0022_candidate_is_processing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateGatheringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_gathering_sessions', to='agency.agency')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_gathering_sessions', to='agency.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_gathering_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Gathering Session',
                'verbose_name_plural': 'Candidate Gathering Sessions',
                'db_table': 'candidate_gathering_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
