# Generated by Django 6.0.4 on 2026-07-25 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0023_candidategatheringsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('current_salary', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=50, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='candidates/resumes')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('ai_extracted_raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agency.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_versions', to='agency.job')),
            ],
            options={
                'verbose_name': 'Candidate Version',
                'verbose_name_plural': 'Candidate Versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
