# Generated by Django 6.0.4 on 2026-07-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0024_candidateversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('hybrid', 'Hybrid'), ('remote', 'Remote'), ('onsite', 'On-site'), ('contract', 'Contract')], default='full-time', max_length=20),
        ),
    ]
