# Generated by Django 6.0.4 on 2026-09-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0028_remove_candidate_ai_extracted_raw_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidateversion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
