# Generated by Django 6.0.4 on 2026-09-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0029_alter_candidateprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateaianalysis',
            name='certification_match',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='certification_weight',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_weight',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='job',
            name='location_weight',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_weight',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_weight',
            field=models.FloatField(default=20.0),
        ),
    ]
