# Generated by Django 6.0.4 on 2026-10-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0030_candidateaianalysis_certification_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgenerationsession',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
