# Generated by Django 6.0.4 on 2026-06-20 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0009_alter_note_model_candidate_candidateactivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('zoom', 'Zoom'), ('outlook', 'Outlook'), ('google_calendar', 'Google Calendar')], max_length=30)),
                ('is_connected', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='agency.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'db_table': 'integrations',
                'unique_together': {('user', 'agency', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='ZoomToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(default='bearer', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('scope', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_token', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'Zoom Token',
                'verbose_name_plural': 'Zoom Tokens',
                'db_table': 'zoom_tokens',
            },
        ),
    ]
