# Generated by Django 6.0.4 on 2026-09-23 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('microsoft', 'Microsoft'), ('google_calendar', 'Google Calendar')], max_length=30),
        ),
        migrations.CreateModel(
            name='MicrosoftToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(default='Bearer', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('scope', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_token', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'Microsoft Token',
                'verbose_name_plural': 'Microsoft Tokens',
                'db_table': 'microsoft_tokens',
            },
        ),
    ]
