# Generated by Django 6.0.4 on 2026-06-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=10),
        ),
    ]
